config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  devise_for :users
  root to: 'servers#index'

  post '/google_drive/webhook', to: 'webhooks#receive'

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :servers, exept: %i[index]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
# frozen_string_literal: true

class Document < ApplicationRecord
  belongs_to :folder
end

app/models/folder.rb
# frozen_string_literal: true

class Folder < ApplicationRecord
  belongs_to :server, optional: true
  has_many :documents, dependent: :destroy
  has_many :subfolders, class_name: 'Folder', foreign_key: 'parent_folder_id', dependent: :destroy
  belongs_to :parent_folder, class_name: 'Folder', optional: true
end

app/models/server.rb
# frozen_string_literal: true

class Server < ApplicationRecord
  belongs_to :user
  has_one :root_folder, -> { where(root_folder: true) }, class_name: 'Folder', dependent: :destroy
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    email == 'florent.guilbaud@gmail.com'
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/servers_controller.rb
# frozen_string_literal: true

class ServersController < ApplicationController
  def index
    @servers = Server.all
  end

  def show
    @server = Server.find(params[:id])
  end

  def new
    @server = Server.new
  end

  def edit; end

  def update; end

  def create
    @server = Server.new(server_params)
    @server.user = current_user
    ids = DiscordServices::Drive.new.create_root_folder(@server.name)

    @server.tracks_folder_id = ids[:tracks]
    @server.root_folder_id = ids[:root]
    root_folder = Folder.create(root_folder: true, server: @server, drive_folder_id: ids[:root])
    tracks_folder = Folder.create(server: @server, drive_folder_id: ids[:tracks], parent_folder_id: root_folder.id, name: "Tracks")
    root_folder.subfolders << tracks_folder
    root_folder.save
    if @server.save
      redirect_to servers_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy; end

  private

  def server_params
    params.require(:server).permit(:name, :token)
  end
end

app/controllers/webhooks_controller.rb
# frozen_string_literal: true

class WebhooksController < ApplicationController
  skip_before_action :authenticate_user!, :verify_authenticity_token
  require 'google/apis/drive_v3'

  SCOPE = Google::Apis::DriveV3::AUTH_DRIVE

  def key
    {
      "type": 'service_account',
      "project_id": 'taotips-393110',
      "private_key_id": Rails.application.credentials.google_drive.private_key_id,
      "private_key": Rails.application.credentials.google_drive.private_key.gsub('\\n', "\n"),
      "client_email": Rails.application.credentials.google_drive.client_email,
      "client_id": Rails.application.credentials.google_drive.client_id,
      "auth_uri": 'https://accounts.google.com/o/oauth2/auth',
      "token_uri": 'https://oauth2.googleapis.com/token',
      "auth_provider_x509_cert_url": 'https://www.googleapis.com/oauth2/v1/certs',
      "client_x509_cert_url": Rails.application.credentials.google_drive.client_x509_cert_url,
      "universe_domain": 'googleapis.com'
    }
  end

  def authorize
    json_key_io = StringIO.new(JSON.generate(key))

    Google::Auth::ServiceAccountCredentials.make_creds(
      json_key_io:,
      scope: SCOPE
    )
  end

  def receive
    channel_id = request.headers['X-Goog-Channel-Id']

    drive_service = Google::Apis::DriveV3::DriveService.new
    drive_service.authorization = authorize

    folder = Folder.find_by(channel_id:)
    return if folder.nil?

    response = drive_service.list_files(q: "'#{folder.drive_folder_id}' in parents",
                                        spaces: 'drive',
                                        fields: 'nextPageToken, files(id, name, mimeType)')

    # Convertir les fichiers de réponse en un hash avec des clés ID pour une recherche facile
    response_files_hash = response.files.index_by(&:id)

    # Boucle à travers les fichiers existants de folder.drive_files
    folder.documents.each do |file|
      # Si un fichier existant n'est pas dans response.files, alors il a été supprimé
      unless response_files_hash[file.drive_file_id]
        puts "Fichier supprimé: #{file.name}"
        file.destroy # ou marquez-le comme supprimé, selon vos besoins
      end
      # Retirer le fichier de response_files_hash pour ne pas le traiter à nouveau
      response_files_hash.delete(file.drive_file_id)
    end

    # Maintenant, response_files_hash ne contient que les nouveaux fichiers
    response_files_hash.each_value do |new_file|
      folder.documents.create(drive_file_id: new_file.id, name: new_file.name)  # ajoutez d'autres attributs si nécessaire
      DiscordServices::SendMessage.new(folder.webhook_url,
                                       "Nouveau #{type(new_file.mime_type)} #{new_file.name} ajouté au drive:", new_file).call
    end

    render json: {}, status: :ok
  end

  def type(type)
    case type
    when 'application/vnd.google-apps.folder'
      'dossier'
    else
      'fichier'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/servers_helper.rb
# frozen_string_literal: true

module ServersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-white">
  <head>
    <title>Trackk</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-full">
    <%= render "shared/navbar" %>
    <div class="h-full <%= "mx-auto pt-10 max-w-7xl" if current_user %>">
      <%= yield %>
    </div>
  </body>
</html>

app/views/servers/edit.html.erb
<h1>Servers#edit</h1>
<p>Find me in app/views/servers/edit.html.erb</p>

app/views/servers/index.html.erb
<h2 class="text-sm font-medium text-gray-500">Pinned Projects</h2>
<ul role="list" class="mt-3 grid grid-cols-1 gap-5 sm:grid-cols-2 sm:gap-6 lg:grid-cols-4">
  <% @servers.each do |server| %>

    <li class="col-span-1 flex rounded-md shadow-sm">
      <%= link_to server.name.first(2).upcase, server_path(server), class: "flex w-16 flex-shrink-0 items-center justify-center bg-purple-600 rounded-l-md text-sm font-medium text-white" %>
      <div class="flex flex-1 items-center justify-between truncate rounded-r-md border-b border-r border-t border-gray-200 bg-white">
        <div class="flex-1 truncate px-4 py-2 text-sm">
          <a href="#" class="font-medium text-gray-900 hover:text-gray-600"><%= server.name %></a>
          <p class="text-gray-500">4 Members</p>
        </div>
        <div class="flex-shrink-0 pr-2">
          <button type="button" class="inline-flex h-8 w-8 items-center justify-center rounded-full bg-transparent bg-white text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
            <span class="sr-only">Open options</span>
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M10 3a1.5 1.5 0 110 3 1.5 1.5 0 010-3zM10 8.5a1.5 1.5 0 110 3 1.5 1.5 0 010-3zM11.5 15.5a1.5 1.5 0 10-3 0 1.5 1.5 0 003 0z" />
            </svg>
          </button>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/servers/new.html.erb
<div class="max-w-xl pt-10 mx-auto">
  <%= simple_form_for @server do |field| %>
    <%= field.input :name, placeholder: "Nom du server" %>
    <%= field.input :token, placeholder: "Id du server" %>
    <%= field.submit class: "btn btn-primary" %>
  <% end %>
</div>

app/views/servers/show.html.erb
<div>
  <div class="px-4 sm:px-0">
    <h3 class="text-base font-semibold leading-7 text-gray-900"><%= @server.name %></h3>
  </div>
  <div class="mt-6 border-t border-gray-100">
    <dl class="divide-y divide-gray-100">
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-sm font-medium leading-6 text-gray-900">Token</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0"><%= @server.token %></dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-sm font-medium leading-6 text-gray-900">Dossier source</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= link_to @server.name.capitalize, "https://drive.google.com/drive/folders/#{@server.root_folder_id}", class: "btn" %>
        </dd>
      </div>
      <div class="px-4 py-6 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-0">
        <dt class="text-sm font-medium leading-6 text-gray-900">Dossier des tracks</dt>
        <dd class="mt-1 text-sm leading-6 text-gray-700 sm:col-span-2 sm:mt-0">
          <%= link_to "Tracks", "https://drive.google.com/drive/folders/#{@server.tracks_folder_id}", class: "btn" %>
        </dd>
      </div>
    </dl>
  </div>
</div>


<% @server.root_folder.subfolders.each do |folder| %>
  <ul role="list" class="divide-y divide-gray-100">
    <li class="flex items-center justify-between gap-x-6 py-5">
      <div class="min-w-0">
        <div class="flex items-start gap-x-3">
          <p class="text-sm font-semibold leading-6 text-gray-900"><%= folder.name %></p>
        </div>
      </div>
    </li>
  </ul>
  <div class="ml-8">
    <% folder.subfolders.each do |subfolder| %>
      <ul role="list" class="divide-y divide-gray-100">
        <li class="flex items-center justify-between gap-x-6 py-5">
          <div class="min-w-0">
            <div class="flex items-start gap-x-3">
              <p class="text-sm font-semibold leading-6 text-gray-900"><%= subfolder.name %></p>
              <%# <p class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-yellow-800 bg-yellow-50 ring-yellow-600/20">Archived</p> %>
            </div>
            <div class="mt-1 flex items-center gap-x-2 text-xs leading-5 text-gray-500">
              <p class="whitespace-nowrap"><%= subfolder.webhook_url %></p>
              <svg viewBox="0 0 2 2" class="h-0.5 w-0.5 fill-current">
                <circle cx="1" cy="1" r="1" />
              </svg>
              <%# <p class="truncate">Created by Courtney Henry</p> %>
            </div>
          </div>
        </li>
      </ul>
      <div class="ml-8">
        <% subfolder.subfolders.each do |content_folder| %>
          <ul role="list" class="divide-y divide-gray-100">
            <li class="flex items-center justify-between gap-x-6 py-5">
              <div class="min-w-0">
                <div class="flex items-start gap-x-3">
                  <p class="text-sm font-semibold leading-6 text-gray-900"><%= content_folder.name %></p>
                  <%# <p class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-yellow-800 bg-yellow-50 ring-yellow-600/20">Archived</p> %>
                </div>
                <div class="mt-1 flex items-center gap-x-2 text-xs leading-5 text-gray-500">
                  <p class="whitespace-nowrap"><%= content_folder.webhook_url %></p>
                  <svg viewBox="0 0 2 2" class="h-0.5 w-0.5 fill-current">
                    <circle cx="1" cy="1" r="1" />
                  </svg>
                  <%# <p class="truncate">Created by Courtney Henry</p> %>
                </div>
              </div>
            </li>
          </ul>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_user %>
  <nav class="bg-white shadow" data-controller="navbar">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 justify-between">
        <div class="flex">
          <div class="-ml-2 mr-2 flex items-center md:hidden">
            <!-- Mobile menu button -->
            <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-secondary" aria-controls="mobile-menu" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <!--
                Icon when menu is closed.

                Menu open: "hidden", Menu closed: "block"
              -->
              <svg class="block h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
              </svg>
              <!--
                Icon when menu is open.

                Menu open: "block", Menu closed: "hidden"
              -->
              <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div class="flex flex-shrink-0 items-center">
            <%# <img class="h-8 w-auto" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company"> %>
            <h1 class="text-3xl font-bold text-primary">TaoTips</h1>
          </div>
          <div class="hidden md:ml-6 md:flex md:space-x-8">
            <!-- Current: "border-secondary text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
            <%= link_to "Servers", servers_path, class: "inline-flex items-center border-b-2 border-secondary px-1 pt-1 text-sm font-medium text-gray-900" %>
            <%# <a href="#" class="inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">Team</a>
            <a href="#" class="inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">Projects</a>
            <a href="#" class="inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700">Calendar</a> %>
          </div>
        </div>
        <div class="flex items-center">
          <div class="flex-shrink-0">
            <%= link_to new_server_path do %>
              <button type="button" class="relative inline-flex items-center gap-x-1.5 rounded-md bg-primary px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-secondary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary">
                <svg class="-ml-0.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                </svg>
                Nouveau server
              </button>
            <% end %>
          </div>
          <div class="hidden md:ml-4 md:flex md:flex-shrink-0 md:items-center">
            <button type="button" class="rounded-full bg-white p-1 text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-secondary focus:ring-offset-2">
              <span class="sr-only">View notifications</span>
              <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
              </svg>
            </button>

            <!-- Profile dropdown -->
            <div class="relative ml-3">
              <div>
                <button data-action="click->navbar#display" type="button" class="flex rounded-full bg-white text-sm focus:outline-none focus:ring-2 focus:ring-secondary focus:ring-offset-2" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                  <span class="sr-only">Open user menu</span>
                  <img class="h-8 w-8 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                </button>
              </div>

              <!--
                Dropdown menu, show/hide based on menu state.

                Entering: "transition ease-out duration-200"
                  From: "transform opacity-0 scale-95"
                  To: "transform opacity-100 scale-100"
                Leaving: "transition ease-in duration-75"
                  From: "transform opacity-100 scale-100"
                  To: "transform opacity-0 scale-95"
              -->
              <div data-navbar-target="menu" class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
                <!-- Active: "bg-gray-100", Not Active: "" -->
                <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-1">Settings</a>
                <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800 sm:px-6"  %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Mobile menu, show/hide based on menu state. -->
    <div class="md:hidden" id="mobile-menu">
      <div class="space-y-1 pb-3 pt-2">
        <!-- Current: "bg-indigo-50 border-secondary text-indigo-700", Default: "border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700" -->
        <a href="#" class="block border-l-4 border-secondary bg-indigo-50 py-2 pl-3 pr-4 text-base font-medium text-indigo-700 sm:pl-5 sm:pr-6">Dashboard</a>
        <a href="#" class="block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700 sm:pl-5 sm:pr-6">Team</a>
        <a href="#" class="block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700 sm:pl-5 sm:pr-6">Projects</a>
        <a href="#" class="block border-l-4 border-transparent py-2 pl-3 pr-4 text-base font-medium text-gray-500 hover:border-gray-300 hover:bg-gray-50 hover:text-gray-700 sm:pl-5 sm:pr-6">Calendar</a>
      </div>
      <div class="border-t border-gray-200 pb-3 pt-4">
        <div class="flex items-center px-4 sm:px-6">
          <div class="flex-shrink-0">
            <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          </div>
          <div class="ml-3">
            <div class="text-base font-medium text-gray-800">Tom Cook</div>
            <div class="text-sm font-medium text-gray-500">tom@example.com</div>
          </div>
          <button type="button" class="ml-auto flex-shrink-0 rounded-full bg-white p-1 text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-secondary focus:ring-offset-2">
            <span class="sr-only">View notifications</span>
            <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
            </svg>
          </button>
        </div>
        <div class="mt-3 space-y-1">
          <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800 sm:px-6">Your Profile</a>
          <a href="#" class="block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800 sm:px-6">Settings</a>
          <%= link_to "Déconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "block px-4 py-2 text-base font-medium text-gray-500 hover:bg-gray-100 hover:text-gray-800 sm:px-6"  %>
        </div>
      </div>
    </div>
  </nav>
<% end %>